Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/graceliu/Library/Python/3.11/lib/python/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbclient/client.py", line 650, in async_setup_kernel
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%%R
##Q1
freq <-c(175,116,131,17,160,126,135,21,132,120,154,29,13,19,40,5,5,9,33,3,22,29,110,6)
op <- factor(rep(1:4,6))
gender <- factor(rep(1:2,each=12))
year <-factor(rep(rep(1:3,each=4),2))

mod1 <- glm(freq~gender+year+op, family=poisson)
deviance(mod1)
summary(mod1)

mod2 <- glm(freq~gender*year+op, family=poisson)
summary(mod2)
mod3 <- glm(freq~gender*op+year, family=poisson)
summary(mod3)
mod4 <- glm(freq~gender+year*op, family=poisson)
summary(mod4)
mod5 <- glm(freq~gender*year+gender*op, family=poisson)
summary(mod5)
mod6 <- glm(freq~gender*year+year*op, family=poisson)
summary(mod6)
mod7 <- glm(freq~gender*op+year*op, family=poisson)
summary(mod7)
mod8 <- glm(freq~gender*year+gender*op+year*op, family=poisson)
summary(mod8)
------------------

----- stderr -----
UsageError: Cell magic `%%R` not found.
------------------



